[package]
name = "hold_launchpad"
version = "0.1.0"
description = "Bonding curve launchpad with pool-level sell rate limit"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "hold_launchpad"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "1.1.2", features = ["init-if-needed"] }
anchor-spl = "1.1.2"
